"""init

Revision ID: 01475368aa45
Revises: 2184df52e788
Create Date: 2023-08-19 21:08:52.405150

"""

# revision identifiers, used by Alembic.
revision = '01475368aa45'
down_revision = '2184df52e788'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
