"""init

Revision ID: 05999a8ac65a
Revises: c9c5e9287f55
Create Date: 2023-08-19 22:34:41.469842

"""

# revision identifiers, used by Alembic.
revision = '05999a8ac65a'
down_revision = 'c9c5e9287f55'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
