"""init

Revision ID: 1065e44ed0cd
Revises: a0da05e27864
Create Date: 2023-08-19 17:52:02.492696

"""

# revision identifiers, used by Alembic.
revision = '1065e44ed0cd'
down_revision = 'a0da05e27864'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
