"""init

Revision ID: 1e04a385848b
Revises: 4c8dffe80dd9
Create Date: 2023-08-19 21:25:22.517032

"""

# revision identifiers, used by Alembic.
revision = '1e04a385848b'
down_revision = '4c8dffe80dd9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
