"""init

Revision ID: 1ea00de5628d
Revises: 85f3f247bf01
Create Date: 2023-08-19 17:51:01.519964

"""

# revision identifiers, used by Alembic.
revision = '1ea00de5628d'
down_revision = '85f3f247bf01'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
