"""init

Revision ID: 2184df52e788
Revises: c72bc2344686
Create Date: 2023-08-19 21:06:14.193799

"""

# revision identifiers, used by Alembic.
revision = '2184df52e788'
down_revision = 'c72bc2344686'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
