"""init

Revision ID: 221cb134c9ee
Revises: 3249797c86c0
Create Date: 2023-08-19 18:03:01.186052

"""

# revision identifiers, used by Alembic.
revision = '221cb134c9ee'
down_revision = '3249797c86c0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
