"""init

Revision ID: 25a9cf19d3cc
Revises: b206076ef45d
Create Date: 2023-08-19 21:21:53.351014

"""

# revision identifiers, used by Alembic.
revision = '25a9cf19d3cc'
down_revision = 'b206076ef45d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
