"""init

Revision ID: 2872f150089f
Revises: cf4141d2d6b0
Create Date: 2023-08-19 20:58:02.187181

"""

# revision identifiers, used by Alembic.
revision = '2872f150089f'
down_revision = 'cf4141d2d6b0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
