"""init

Revision ID: 3249797c86c0
Revises: d92a3f694abf
Create Date: 2023-08-19 17:54:41.921115

"""

# revision identifiers, used by Alembic.
revision = '3249797c86c0'
down_revision = 'd92a3f694abf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
