"""init

Revision ID: 3e9154b80cde
Revises: ae881e5b8c16
Create Date: 2023-08-19 17:49:03.229971

"""

# revision identifiers, used by Alembic.
revision = '3e9154b80cde'
down_revision = 'ae881e5b8c16'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
