"""init

Revision ID: 4aa99ae78142
Revises: da292db899ea
Create Date: 2023-08-19 20:50:13.685267

"""

# revision identifiers, used by Alembic.
revision = '4aa99ae78142'
down_revision = 'da292db899ea'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
