"""init

Revision ID: 4b619cac0f49
Revises: 6dd0f28dfb44
Create Date: 2023-08-19 17:47:33.036364

"""

# revision identifiers, used by Alembic.
revision = '4b619cac0f49'
down_revision = '6dd0f28dfb44'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
