"""init

Revision ID: 4c8dffe80dd9
Revises: 25a9cf19d3cc
Create Date: 2023-08-19 21:24:08.550177

"""

# revision identifiers, used by Alembic.
revision = '4c8dffe80dd9'
down_revision = '25a9cf19d3cc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
