"""init

Revision ID: 572326bcb774
Revises: bae065f43b9e
Create Date: 2023-08-19 21:19:37.782144

"""

# revision identifiers, used by Alembic.
revision = '572326bcb774'
down_revision = 'bae065f43b9e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
