"""init

Revision ID: 64f7d4500fac
Revises: cbacbd79a5de
Create Date: 2023-08-19 21:28:58.187519

"""

# revision identifiers, used by Alembic.
revision = '64f7d4500fac'
down_revision = 'cbacbd79a5de'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
