"""init

Revision ID: 6a5208d9a431
Revises: b8005607f5fb
Create Date: 2023-08-19 21:13:37.649587

"""

# revision identifiers, used by Alembic.
revision = '6a5208d9a431'
down_revision = 'b8005607f5fb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
