"""init

Revision ID: 6dd0f28dfb44
Revises: f71d62aa02bd
Create Date: 2023-08-19 17:16:52.706750

"""

# revision identifiers, used by Alembic.
revision = '6dd0f28dfb44'
down_revision = 'f71d62aa02bd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
