"""init

Revision ID: 7db36f6ec772
Revises: dd33cb03d01f
Create Date: 2023-08-18 19:23:02.561645

"""

# revision identifiers, used by Alembic.
revision = '7db36f6ec772'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
