"""init

Revision ID: 85f3f247bf01
Revises: 3e9154b80cde
Create Date: 2023-08-19 17:49:44.807143

"""

# revision identifiers, used by Alembic.
revision = '85f3f247bf01'
down_revision = '3e9154b80cde'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
