"""init

Revision ID: 911ff6d09b45
Revises: 2872f150089f
Create Date: 2023-08-19 20:58:47.379890

"""

# revision identifiers, used by Alembic.
revision = '911ff6d09b45'
down_revision = '2872f150089f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
