"""init

Revision ID: 91b975d12d4a
Revises: c9e3a2876f18
Create Date: 2023-08-19 21:12:21.544806

"""

# revision identifiers, used by Alembic.
revision = '91b975d12d4a'
down_revision = 'c9e3a2876f18'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
