"""init

Revision ID: 9edd20e7c6d2
Revises: 4aa99ae78142
Create Date: 2023-08-19 20:52:21.418610

"""

# revision identifiers, used by Alembic.
revision = '9edd20e7c6d2'
down_revision = '4aa99ae78142'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
