"""init

Revision ID: a0da05e27864
Revises: 1ea00de5628d
Create Date: 2023-08-19 17:51:53.878442

"""

# revision identifiers, used by Alembic.
revision = 'a0da05e27864'
down_revision = '1ea00de5628d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
