"""init

Revision ID: ae881e5b8c16
Revises: 4b619cac0f49
Create Date: 2023-08-19 17:48:09.750455

"""

# revision identifiers, used by Alembic.
revision = 'ae881e5b8c16'
down_revision = '4b619cac0f49'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
