"""init

Revision ID: b206076ef45d
Revises: 572326bcb774
Create Date: 2023-08-19 21:20:58.948253

"""

# revision identifiers, used by Alembic.
revision = 'b206076ef45d'
down_revision = '572326bcb774'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
