"""init

Revision ID: b8005607f5fb
Revises: 91b975d12d4a
Create Date: 2023-08-19 21:13:22.356060

"""

# revision identifiers, used by Alembic.
revision = 'b8005607f5fb'
down_revision = '91b975d12d4a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
