"""init

Revision ID: b860ae64baf6
Revises: 6a5208d9a431
Create Date: 2023-08-19 21:15:09.433624

"""

# revision identifiers, used by Alembic.
revision = 'b860ae64baf6'
down_revision = '6a5208d9a431'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
