"""init

Revision ID: b875246324e3
Revises: 1065e44ed0cd
Create Date: 2023-08-19 17:53:04.604767

"""

# revision identifiers, used by Alembic.
revision = 'b875246324e3'
down_revision = '1065e44ed0cd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
