"""init

Revision ID: bae065f43b9e
Revises: ead0ff8f6c9d
Create Date: 2023-08-19 21:18:40.880670

"""

# revision identifiers, used by Alembic.
revision = 'bae065f43b9e'
down_revision = 'ead0ff8f6c9d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
