"""init

Revision ID: c72bc2344686
Revises: 911ff6d09b45
Create Date: 2023-08-19 21:03:56.363184

"""

# revision identifiers, used by Alembic.
revision = 'c72bc2344686'
down_revision = '911ff6d09b45'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
