"""init

Revision ID: c9c5e9287f55
Revises: df781817aeb4
Create Date: 2023-08-19 22:29:57.786331

"""

# revision identifiers, used by Alembic.
revision = 'c9c5e9287f55'
down_revision = 'df781817aeb4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
