"""init

Revision ID: c9e3a2876f18
Revises: 01475368aa45
Create Date: 2023-08-19 21:11:35.813911

"""

# revision identifiers, used by Alembic.
revision = 'c9e3a2876f18'
down_revision = '01475368aa45'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
