"""init

Revision ID: cbacbd79a5de
Revises: 1e04a385848b
Create Date: 2023-08-19 21:26:54.269029

"""

# revision identifiers, used by Alembic.
revision = 'cbacbd79a5de'
down_revision = '1e04a385848b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
