"""init

Revision ID: cf4141d2d6b0
Revises: 9edd20e7c6d2
Create Date: 2023-08-19 20:56:53.188929

"""

# revision identifiers, used by Alembic.
revision = 'cf4141d2d6b0'
down_revision = '9edd20e7c6d2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
