"""init

Revision ID: d92a3f694abf
Revises: b875246324e3
Create Date: 2023-08-19 17:53:54.840987

"""

# revision identifiers, used by Alembic.
revision = 'd92a3f694abf'
down_revision = 'b875246324e3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
