"""init

Revision ID: da292db899ea
Revises: 221cb134c9ee
Create Date: 2023-08-19 19:06:39.899947

"""

# revision identifiers, used by Alembic.
revision = 'da292db899ea'
down_revision = '221cb134c9ee'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
