"""init

Revision ID: df781817aeb4
Revises: 64f7d4500fac
Create Date: 2023-08-19 21:51:02.238119

"""

# revision identifiers, used by Alembic.
revision = 'df781817aeb4'
down_revision = '64f7d4500fac'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
