"""init

Revision ID: ead0ff8f6c9d
Revises: b860ae64baf6
Create Date: 2023-08-19 21:17:20.248698

"""

# revision identifiers, used by Alembic.
revision = 'ead0ff8f6c9d'
down_revision = 'b860ae64baf6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
