"""init

Revision ID: f71d62aa02bd
Revises: 7db36f6ec772
Create Date: 2023-08-19 10:46:30.287836

"""

# revision identifiers, used by Alembic.
revision = 'f71d62aa02bd'
down_revision = '7db36f6ec772'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
